### ISSUE TITLE
Crash in VS2017 Update 4 with C++

### ISSUE THREAD

**Issue by Suchiman** [tomasr/viasfora#223]
I'm not sure if this is actually comming from Viasfora but Visual Studio pointed out that Viasfora might have caused the crash and its in the Stacktrace. I couldn't reproduce it a second time by redoing my steps so... Based on the StackTrace (crashing in HashTable.Insert) i would estimate that its a concurrency issue.
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Collections.Hashtable.Insert(System.Object, System.Object, Boolean)
   at System.Collections.Hashtable.Add(System.Object, System.Object)
   at System.Collections.Specialized.HybridDictionary.Add(System.Object, System.Object)
   at Microsoft.VisualStudio.Utilities.PropertyCollection.AddProperty(System.Object, System.Object)
   at Winterdom.Viasfora.CommonExtensions.Set[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.VisualStudio.Utilities.IPropertyOwner, System.__Canon)
   at Winterdom.Viasfora.Util.ToolTipWindow.GetWindow(Microsoft.VisualStudio.Text.SnapshotPoint)
   at Winterdom.Viasfora.Rainbow.RainbowToolTipSource.AugmentQuickInfoSession(Microsoft.VisualStudio.Language.Intellisense.IQuickInfoSession, System.Collections.Generic.IList`1<System.Object>, Microsoft.VisualStudio.Text.ITrackingSpan ByRef)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start()
   at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource+<>c__DisplayClass11_0.<RetrySession>b__0(System.Object, System.EventArgs)
   at System.Windows.Threading.DispatcherTimer.FireTick(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by tomasr** [comment]
Thanks for reporting, @Suchiman 

If you run into it again, could you let me know sort of what you were doing when it happened? Based on the stack trace, it looks like it is related to displaying rainbow braces tooltips. It definitely looks like it is trying to register something twice, so that's going to be.... fun to diagnose.

I'll take a look later today and see what I can spot.

**Comment by Suchiman** [comment]
I wanted to select text and i think i've seen a peek window for a fraction of a second before i could start selecting.

**Comment by tomasr** [comment]
I've been trying to reproduce this without success right now. The only way I see this being an issue is a race condition between one quick-info session being created while the `Dismiss()` hasn't been called yet for the previous tooltip (wouldn't need multiple threads, just reentrancy).

I've changed the code to avoid having to add a new property to the text view when the quick-info session is created, so hopefully this clears up the issue in any case. Let me know how that works for you.
