### ISSUE TITLE
Installation in VS2019 fails

### ISSUE THREAD

**Issue by narayagh** [tomasr/viasfora#274]
Installation in VS2019 Community fails with **Element not found** error.

Install log:
```
28/05/2019 14:19:59 - Microsoft VSIX Installer
28/05/2019 14:19:59 - -------------------------------------------
28/05/2019 14:19:59 - vsixinstaller.exe version:
28/05/2019 14:19:59 - 16.0.2268
28/05/2019 14:19:59 - -------------------------------------------
28/05/2019 14:19:59 - Command line parameters:
28/05/2019 14:19:59 - C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe,/skuName:Community,/skuVersion:16.0.28803.352,/appidname:Microsoft Visual Studio Community 2019,/culture:en-US,/noep,C:\Users\MIKE\AppData\Local\Temp\VSIXnlvhv454.vsix
28/05/2019 14:19:59 - -------------------------------------------
28/05/2019 14:19:59 - Microsoft VSIX Installer
28/05/2019 14:19:59 - -------------------------------------------
28/05/2019 14:19:59 - Initializing Install...
28/05/2019 14:19:59 - Extension Details...
28/05/2019 14:19:59 - 	Identifier         : Winterdom.Viasfora.f7a33795-2b40-4125-856c-89b0bd8cd5ab
28/05/2019 14:19:59 - 	Name               : Viasfora
28/05/2019 14:19:59 - 	Author             : Tomas Restrepo
28/05/2019 14:19:59 - 	Version            : 4.2.188
28/05/2019 14:19:59 - 	Description        : Add color to your Visual Studio Text Editor!
28/05/2019 14:19:59 - 	Locale             : en-US
28/05/2019 14:19:59 - 	MoreInfoURL        : http://viasfora.com/
28/05/2019 14:19:59 - 	InstalledByMSI     : False
28/05/2019 14:19:59 - 	SupportedFrameworkVersionRange : [4.5,)
28/05/2019 14:19:59 - 
28/05/2019 14:19:59 - 	SignatureState     : Unsigned
28/05/2019 14:19:59 - 	Supported Products : 
28/05/2019 14:19:59 - 		Microsoft.VisualStudio.Community
28/05/2019 14:19:59 - 			Version : [14.0,17.0)
28/05/2019 14:19:59 - 		Microsoft.VisualStudio.Pro
28/05/2019 14:19:59 - 			Version : [11.0,17.0)
28/05/2019 14:19:59 - 		Microsoft.VisualStudio.Enterprise
28/05/2019 14:19:59 - 			Version : [11.0,16.0)
28/05/2019 14:19:59 - 		Microsoft.VisualStudio.IntegratedShell
28/05/2019 14:19:59 - 			Version : [11.0,17.0)
28/05/2019 14:19:59 - 		Microsoft.VisualStudio.Ultimate
28/05/2019 14:19:59 - 			Version : [11.0,17.0)
28/05/2019 14:19:59 - 		Microsoft.VisualStudio.Premium
28/05/2019 14:19:59 - 			Version : [11.0,17.0)
28/05/2019 14:19:59 - 
28/05/2019 14:19:59 - 	References         : 
28/05/2019 14:19:59 - 	Prerequisites      : 
28/05/2019 14:19:59 - 		-------------------------------------------------------
28/05/2019 14:19:59 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
28/05/2019 14:19:59 - 		Name         : Visual Studio core editor
28/05/2019 14:19:59 - 		Version      : [15.0,17.0)
28/05/2019 14:19:59 - 
28/05/2019 14:19:59 - Signature Details...
28/05/2019 14:19:59 - 	Extension is not signed.
28/05/2019 14:19:59 - 
28/05/2019 14:19:59 - System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)
   at Microsoft.VisualStudio.Setup.Configuration.ISetupConfiguration2.GetInstanceForPath(String path)
   at VSIXInstaller.LocationBasedSKU..ctor(String appidInstallPath, String appidName, Version vsVersion, String edition, String rootSuffix)
   at VSIXInstaller.LocationBasedSKU..ctor(String appidInstallPath, String appidName, Version vsVersion, String edition, String rootSuffix, IntPtr alternateUserToken)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.ComputeInstallableExtensions(IStateData stateData, Boolean isRepairSupported, Boolean isExtensionPack, IDictionary`2 skuDataMapping, IList`1 installableExtensionsPaths)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by tomasr** [comment]
First time I've seen this, but it doesn't sound like an issue on Viasfora's side.

It would appear something is corrupted on your VS installation, since vsixinstaller can't find where it is installed.

You haven't been using one of those registry cleaner tools, or something like it by any chance?

**Comment by narayagh** [comment]
My VS Installer was broken. After reinstalling VS2019 from scratch everything works fine. Love the extension!
